# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: condlayers/condlayers.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'condlayers/condlayers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ondlayers/condlayers.proto\x12\x0ezmk.condlayers\"Y\n\rCondLayerInfo\x12\r\n\x05index\x18\x01 \x01(\r\x12\x16\n\x0eif_layers_mask\x18\x02 \x01(\r\x12\x12\n\nthen_layer\x18\x03 \x01(\x05\x12\r\n\x05\x66ound\x18\x04 \x01(\x08\"\x07\n\x05\x45mpty\"\x1c\n\x0bSlotRequest\x12\r\n\x05index\x18\x01 \x01(\r\"G\n\nSetRequest\x12\r\n\x05index\x18\x01 \x01(\r\x12\x16\n\x0eif_layers_mask\x18\x02 \x01(\r\x12\x12\n\nthen_layer\x18\x03 \x01(\x05\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"\'\n\nOkResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\r\"\xc6\x01\n\x07Request\x12&\n\x05\x63ount\x18\x01 \x01(\x0b\x32\x15.zmk.condlayers.EmptyH\x00\x12*\n\x03get\x18\x02 \x01(\x0b\x32\x1b.zmk.condlayers.SlotRequestH\x00\x12)\n\x03set\x18\x03 \x01(\x0b\x32\x1a.zmk.condlayers.SetRequestH\x00\x12,\n\x05reset\x18\x04 \x01(\x0b\x32\x1b.zmk.condlayers.SlotRequestH\x00\x42\x0e\n\x0crequest_type\"\xd1\x01\n\x08Response\x12.\n\x05\x63ount\x18\x01 \x01(\x0b\x32\x1d.zmk.condlayers.CountResponseH\x00\x12,\n\x03get\x18\x02 \x01(\x0b\x32\x1d.zmk.condlayers.CondLayerInfoH\x00\x12)\n\x03set\x18\x03 \x01(\x0b\x32\x1a.zmk.condlayers.OkResponseH\x00\x12+\n\x05reset\x18\x04 \x01(\x0b\x32\x1a.zmk.condlayers.OkResponseH\x00\x42\x0f\n\rresponse_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'condlayers.condlayers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONDLAYERINFO']._serialized_start=47
  _globals['_CONDLAYERINFO']._serialized_end=136
  _globals['_EMPTY']._serialized_start=138
  _globals['_EMPTY']._serialized_end=145
  _globals['_SLOTREQUEST']._serialized_start=147
  _globals['_SLOTREQUEST']._serialized_end=175
  _globals['_SETREQUEST']._serialized_start=177
  _globals['_SETREQUEST']._serialized_end=248
  _globals['_COUNTRESPONSE']._serialized_start=250
  _globals['_COUNTRESPONSE']._serialized_end=280
  _globals['_OKRESPONSE']._serialized_start=282
  _globals['_OKRESPONSE']._serialized_end=321
  _globals['_REQUEST']._serialized_start=324
  _globals['_REQUEST']._serialized_end=522
  _globals['_RESPONSE']._serialized_start=525
  _globals['_RESPONSE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
