# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zmk/monitor/monitor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zmk/monitor/monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19zmk/monitor/monitor.proto\x12\x0bzmk.monitor\"\x07\n\x05\x45mpty\"\x18\n\nOkResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"+\n\nLayerState\x12\x0c\n\x04mask\x18\x01 \x01(\r\x12\x0f\n\x07highest\x18\x02 \x01(\r\"=\n\x08KeyEvent\x12\x10\n\x08position\x18\x01 \x01(\r\x12\x0f\n\x07pressed\x18\x02 \x01(\x08\x12\x0e\n\x06source\x18\x03 \x01(\r\"W\n\x0cKeycodeEvent\x12\x12\n\nusage_page\x18\x01 \x01(\r\x12\x0f\n\x07keycode\x18\x02 \x01(\r\x12\x0f\n\x07pressed\x18\x03 \x01(\x08\x12\x11\n\tmodifiers\x18\x04 \x01(\r\"\x95\x01\n\x0cNotification\x12$\n\x03key\x18\x01 \x01(\x0b\x32\x15.zmk.monitor.KeyEventH\x00\x12)\n\x06layers\x18\x02 \x01(\x0b\x32\x17.zmk.monitor.LayerStateH\x00\x12,\n\x07keycode\x18\x03 \x01(\x0b\x32\x19.zmk.monitor.KeycodeEventH\x00\x42\x06\n\x04type\"\x90\x01\n\x07Request\x12(\n\nget_layers\x18\x01 \x01(\x0b\x32\x12.zmk.monitor.EmptyH\x00\x12$\n\x06\x65nable\x18\x02 \x01(\x0b\x32\x12.zmk.monitor.EmptyH\x00\x12%\n\x07\x64isable\x18\x03 \x01(\x0b\x32\x12.zmk.monitor.EmptyH\x00\x42\x0e\n\x0crequest_type\"m\n\x08Response\x12)\n\x06layers\x18\x01 \x01(\x0b\x32\x17.zmk.monitor.LayerStateH\x00\x12%\n\x02ok\x18\x02 \x01(\x0b\x32\x17.zmk.monitor.OkResponseH\x00\x42\x0f\n\rresponse_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zmk.monitor.monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=42
  _globals['_EMPTY']._serialized_end=49
  _globals['_OKRESPONSE']._serialized_start=51
  _globals['_OKRESPONSE']._serialized_end=75
  _globals['_LAYERSTATE']._serialized_start=77
  _globals['_LAYERSTATE']._serialized_end=120
  _globals['_KEYEVENT']._serialized_start=122
  _globals['_KEYEVENT']._serialized_end=183
  _globals['_KEYCODEEVENT']._serialized_start=185
  _globals['_KEYCODEEVENT']._serialized_end=272
  _globals['_NOTIFICATION']._serialized_start=275
  _globals['_NOTIFICATION']._serialized_end=424
  _globals['_REQUEST']._serialized_start=427
  _globals['_REQUEST']._serialized_end=571
  _globals['_RESPONSE']._serialized_start=573
  _globals['_RESPONSE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
