# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: macros/macros.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'macros/macros.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13macros/macros.proto\x12\nzmk.macros\"K\n\tMacroStep\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x0f\n\x07keycode\x18\x02 \x01(\r\x12\x0f\n\x07wait_ms\x18\x03 \x01(\r\x12\x0e\n\x06tap_ms\x18\x04 \x01(\r\"\x1f\n\x0fGetMacroRequest\x12\x0c\n\x04slot\x18\x01 \x01(\r\"8\n\x10GetMacroResponse\x12$\n\x05steps\x18\x01 \x03(\x0b\x32\x15.zmk.macros.MacroStep\"E\n\x0fSetMacroRequest\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12$\n\x05steps\x18\x02 \x03(\x0b\x32\x15.zmk.macros.MacroStep\"-\n\x10SetMacroResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\r\"}\n\x07Request\x12\x30\n\tget_macro\x18\x01 \x01(\x0b\x32\x1b.zmk.macros.GetMacroRequestH\x00\x12\x30\n\tset_macro\x18\x02 \x01(\x0b\x32\x1b.zmk.macros.SetMacroRequestH\x00\x42\x0e\n\x0crequest_type\"\x81\x01\n\x08Response\x12\x31\n\tget_macro\x18\x01 \x01(\x0b\x32\x1c.zmk.macros.GetMacroResponseH\x00\x12\x31\n\tset_macro\x18\x02 \x01(\x0b\x32\x1c.zmk.macros.SetMacroResponseH\x00\x42\x0f\n\rresponse_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macros.macros_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MACROSTEP']._serialized_start=35
  _globals['_MACROSTEP']._serialized_end=110
  _globals['_GETMACROREQUEST']._serialized_start=112
  _globals['_GETMACROREQUEST']._serialized_end=143
  _globals['_GETMACRORESPONSE']._serialized_start=145
  _globals['_GETMACRORESPONSE']._serialized_end=201
  _globals['_SETMACROREQUEST']._serialized_start=203
  _globals['_SETMACROREQUEST']._serialized_end=272
  _globals['_SETMACRORESPONSE']._serialized_start=274
  _globals['_SETMACRORESPONSE']._serialized_end=319
  _globals['_REQUEST']._serialized_start=321
  _globals['_REQUEST']._serialized_end=446
  _globals['_RESPONSE']._serialized_start=449
  _globals['_RESPONSE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
