# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: holdtap/holdtap.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'holdtap/holdtap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15holdtap/holdtap.proto\x12\x0bzmk.holdtap\"\x88\x01\n\x0bHoldTapInfo\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12\x17\n\x0ftapping_term_ms\x18\x02 \x01(\x05\x12\x14\n\x0cquick_tap_ms\x18\x03 \x01(\x05\x12\x1d\n\x15require_prior_idle_ms\x18\x04 \x01(\x05\x12\x0e\n\x06\x66lavor\x18\x05 \x01(\r\x12\r\n\x05\x66ound\x18\x06 \x01(\x08\"\x07\n\x05\x45mpty\"\x1b\n\x0bSlotRequest\x12\x0c\n\x04slot\x18\x01 \x01(\r\"x\n\nSetRequest\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12\x17\n\x0ftapping_term_ms\x18\x02 \x01(\x05\x12\x14\n\x0cquick_tap_ms\x18\x03 \x01(\x05\x12\x1d\n\x15require_prior_idle_ms\x18\x04 \x01(\x05\x12\x0e\n\x06\x66lavor\x18\x05 \x01(\r\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"\'\n\nOkResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\r\"\xba\x01\n\x07Request\x12#\n\x05\x63ount\x18\x01 \x01(\x0b\x32\x12.zmk.holdtap.EmptyH\x00\x12\'\n\x03get\x18\x02 \x01(\x0b\x32\x18.zmk.holdtap.SlotRequestH\x00\x12&\n\x03set\x18\x03 \x01(\x0b\x32\x17.zmk.holdtap.SetRequestH\x00\x12)\n\x05reset\x18\x04 \x01(\x0b\x32\x18.zmk.holdtap.SlotRequestH\x00\x42\x0e\n\x0crequest_type\"\xc3\x01\n\x08Response\x12+\n\x05\x63ount\x18\x01 \x01(\x0b\x32\x1a.zmk.holdtap.CountResponseH\x00\x12\'\n\x03get\x18\x02 \x01(\x0b\x32\x18.zmk.holdtap.HoldTapInfoH\x00\x12&\n\x03set\x18\x03 \x01(\x0b\x32\x17.zmk.holdtap.OkResponseH\x00\x12(\n\x05reset\x18\x04 \x01(\x0b\x32\x17.zmk.holdtap.OkResponseH\x00\x42\x0f\n\rresponse_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'holdtap.holdtap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOLDTAPINFO']._serialized_start=39
  _globals['_HOLDTAPINFO']._serialized_end=175
  _globals['_EMPTY']._serialized_start=177
  _globals['_EMPTY']._serialized_end=184
  _globals['_SLOTREQUEST']._serialized_start=186
  _globals['_SLOTREQUEST']._serialized_end=213
  _globals['_SETREQUEST']._serialized_start=215
  _globals['_SETREQUEST']._serialized_end=335
  _globals['_COUNTRESPONSE']._serialized_start=337
  _globals['_COUNTRESPONSE']._serialized_end=367
  _globals['_OKRESPONSE']._serialized_start=369
  _globals['_OKRESPONSE']._serialized_end=408
  _globals['_REQUEST']._serialized_start=411
  _globals['_REQUEST']._serialized_end=597
  _globals['_RESPONSE']._serialized_start=600
  _globals['_RESPONSE']._serialized_end=795
# @@protoc_insertion_point(module_scope)
