# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'custom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ustom.proto\x12\nzmk.custom\"\x1c\n\x1aListCustomSubsystemRequest\"R\n\x1bListCustomSubsystemResponse\x12\x33\n\nsubsystems\x18\x01 \x03(\x0b\x32\x1f.zmk.custom.CustomSubsystemInfo\"H\n\x13\x43ustomSubsystemInfo\x12\r\n\x05index\x18\x01 \x01(\r\x12\x12\n\nidentifier\x18\x02 \x01(\t\x12\x0e\n\x06ui_url\x18\x03 \x03(\t\"7\n\x0b\x43\x61llRequest\x12\x17\n\x0fsubsystem_index\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"8\n\x0c\x43\x61llResponse\x12\x17\n\x0fsubsystem_index\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\">\n\x12\x43ustomNotification\x12\x17\n\x0fsubsystem_index\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x8c\x01\n\x07Request\x12H\n\x16list_custom_subsystems\x18\x01 \x01(\x0b\x32&.zmk.custom.ListCustomSubsystemRequestH\x00\x12\'\n\x04\x63\x61ll\x18\x02 \x01(\x0b\x32\x17.zmk.custom.CallRequestH\x00\x42\x0e\n\x0crequest_type\"\x90\x01\n\x08Response\x12I\n\x16list_custom_subsystems\x18\x01 \x01(\x0b\x32\'.zmk.custom.ListCustomSubsystemResponseH\x00\x12(\n\x04\x63\x61ll\x18\x02 \x01(\x0b\x32\x18.zmk.custom.CallResponseH\x00\x42\x0f\n\rresponse_type\"b\n\x0cNotification\x12=\n\x13\x63ustom_notification\x18\x01 \x01(\x0b\x32\x1e.zmk.custom.CustomNotificationH\x00\x42\x13\n\x11notification_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTCUSTOMSUBSYSTEMREQUEST']._serialized_start=28
  _globals['_LISTCUSTOMSUBSYSTEMREQUEST']._serialized_end=56
  _globals['_LISTCUSTOMSUBSYSTEMRESPONSE']._serialized_start=58
  _globals['_LISTCUSTOMSUBSYSTEMRESPONSE']._serialized_end=140
  _globals['_CUSTOMSUBSYSTEMINFO']._serialized_start=142
  _globals['_CUSTOMSUBSYSTEMINFO']._serialized_end=214
  _globals['_CALLREQUEST']._serialized_start=216
  _globals['_CALLREQUEST']._serialized_end=271
  _globals['_CALLRESPONSE']._serialized_start=273
  _globals['_CALLRESPONSE']._serialized_end=329
  _globals['_CUSTOMNOTIFICATION']._serialized_start=331
  _globals['_CUSTOMNOTIFICATION']._serialized_end=393
  _globals['_REQUEST']._serialized_start=396
  _globals['_REQUEST']._serialized_end=536
  _globals['_RESPONSE']._serialized_start=539
  _globals['_RESPONSE']._serialized_end=683
  _globals['_NOTIFICATION']._serialized_start=685
  _globals['_NOTIFICATION']._serialized_end=783
# @@protoc_insertion_point(module_scope)
